Issure56
MindTheGap-ERC/CarboKitten.jl pull request #59
Opened 2024-09-05 14:06 UTC by xyl96

Improving documentation format for chemical dissolution

2024-09-05 17:58 UTC, jhidding requested changes

2024-09-05 17:58 UTC, jhidding commented on docs/src/denudation/chemical.md
> +Herein $\frac{dh}{dt}$ is the chemical weathering rate and the unit is in m/s.
In inline math it is well accepted to just use a slash for division

2024-09-05 17:58 UTC, jhidding commented on docs/src/denudation/chemical.md
> +$$\kappa_c = 40\times 1000\ \frac{[Ca^{2+}]_{eq}}{ρ}$$
Please refrain from using times operator, just use a spacing, or in this case write 40 000, also the rho is still there

2024-09-05 17:58 UTC, jhidding commented on docs/src/denudation/chemical.md
> +$$c(z) = c_{eq}\ (1 - e^{(\frac{-z}{\lambda})})$$
Superfluous parentheses. In superscript like this I prefer a/b notation for fractions

2024-09-05 18:01 UTC, jhidding commented
Please also run entangled

2024-09-06 09:05 UTC, EmiliaJarochowska commented on docs/src/denudation/chemical.md
> +and ```equlibrium``` function to calculate the $[Ca^{2+}]_{eq}$:
should be `equilibrium` (typo)

2024-09-06 09:06 UTC, EmiliaJarochowska commented on docs/src/denudation/chemical.md
> +$$\kappa_c = 40\times 1000\ \frac{[Ca^{2+}]_{eq}}{ρ}$$
I think this was on me, why is `\times` wrong?

2024-09-06 13:52 UTC, jhidding commented on docs/src/denudation/chemical.md
> +$$\kappa_c = 40\times 1000\ \frac{[Ca^{2+}]_{eq}}{ρ}$$
It's not wrong, just not common where I come from

2024-09-11 09:48 UTC, merged